-- [[ << Assembled file >> glimmer bundle v1 ]]
-- Profiling map transport: plaintext
-- Execution: regenerated Lua (best-effort lowering). Map: server-side symbolication only.

GLIMMER_MAP_MODE = "plaintext"
GLIMMER_PROFILE_MAP_B64 = [[eyJnbGltbWVyX3Byb2ZpbGluZ19tYXAiOjEsInNvdXJjZV9wYXRoIjoiLlxcdGVzdF9jb2RlXFxqaXRfbmVzdGVkX2Nsb3N1cmUubHVhIiwicHJvdG9zIjpbeyJpZCI6MCwiY2h1bmtuYW1lIjoiLlxcdGVzdF9jb2RlXFxqaXRfbmVzdGVkX2Nsb3N1cmUubHVhIiwiZmlyc3RsaW5lIjowLCJudW1saW5lIjo5LCJsaW5lX3Blcl9iYyI6WzAsNiw4LDgsOCw4XX0seyJpZCI6MSwiY2h1bmtuYW1lIjoiLlxcdGVzdF9jb2RlXFxqaXRfbmVzdGVkX2Nsb3N1cmUubHVhIiwiZmlyc3RsaW5lIjoyLCJudW1saW5lIjo0LCJsaW5lX3Blcl9iYyI6WzIsNSw1LDVdfSx7ImlkIjoyLCJjaHVua25hbWUiOiIuXFx0ZXN0X2NvZGVcXGppdF9uZXN0ZWRfY2xvc3VyZS5sdWEiLCJmaXJzdGxpbmUiOjMsIm51bWxpbmUiOjIsImxpbmVfcGVyX2JjIjpbMyw0LDRdfV19]]

-- Regenerated by glimmer (best-effort LuaJIT lowering). Uses `goto` with stable label names.
local __p0, __p1, __p2
__p0 = function()
  local _r0, _r1
  _r0 = __p1
  _r1 = _r0
  local __fn_0_4 = _r1
  _r1 = __fn_0_4()
  ::__p0_x0::
  goto __p0_x0
  return _r1()
end
__p1 = function()
  local _r0
  _r0 = __p2
  ::__p1_x0::
  goto __p1_x0
  return _r0
end
__p2 = function()
  local _r0
  _r0 = 1
  return _r0
end

return (function()
  return __p0()
end)()
