-- [[ << Assembled file >> glimmer bundle v1 ]]
-- Profiling map transport: plaintext
-- Execution: regenerated Lua (best-effort lowering). Map: server-side symbolication only.

GLIMMER_MAP_MODE = "plaintext"
GLIMMER_PROFILE_MAP_B64 = [[eyJnbGltbWVyX3Byb2ZpbGluZ19tYXAiOjEsInNvdXJjZV9wYXRoIjoiLlxcdGVzdF9jb2RlXFxteV9UZXN0Lmx1YSIsInByb3RvcyI6W3siaWQiOjAsImNodW5rbmFtZSI6Ii5cXHRlc3RfY29kZVxcbXlfVGVzdC5sdWEiLCJmaXJzdGxpbmUiOjAsIm51bWxpbmUiOjMxLCJsaW5lX3Blcl9iYyI6WzAsNywyNywyOSwyOSwzMSwzMSwzMV19LHsiaWQiOjEsImNodW5rbmFtZSI6Ii5cXHRlc3RfY29kZVxcbXlfVGVzdC5sdWEiLCJmaXJzdGxpbmUiOjMsIm51bWxpbmUiOjQsImxpbmVfcGVyX2JjIjpbMyw0LDQsNCw1LDUsNSw3XX0seyJpZCI6MiwiY2h1bmtuYW1lIjoiLlxcdGVzdF9jb2RlXFxteV9UZXN0Lmx1YSIsImZpcnN0bGluZSI6MTEsIm51bWxpbmUiOjE2LCJsaW5lX3Blcl9iYyI6WzExLDEyLDEyLDEyLDEzLDEzLDEzLDE2LDE2LDE2LDE3LDE3LDE3LDIwLDIwLDIwLDIxLDIxLDIxLDI0LDI0LDI0LDI1LDI1LDI1LDI3XX1dfQ==]]

-- Regenerated by glimmer (best-effort LuaJIT lowering). CFG: `--! cfg high` → dispatcher; `low`/`none` → `goto` + stable labels.
local __p0, __p1, __p2
__p0 = function()
  local _r0, _r1, _r2
  _r0 = __p1
  _r1 = __p2
  _r2 = _r0
  _r2()
  _r2 = _r1
  _r2()
  return
end
__p1 = function()
  local _r0, _r1
  _r0 = 1
  if _r0 == 1 then
    goto __p1_x0
  else
    goto __p1_x1
  end
  ::__p1_x0::
  _r0 = _G["print"]
  _r1 = "Easy example"
  _r0(_r1)
  ::__p1_x1::
  return
end
__p2 = function()
  local _r0, _r1
  local __dc_2 = 0
  while true do
    if __dc_2 == 0 then
      _r0 = 1
      if _r0 == 1 then
        __dc_2 = 1
      else
        __dc_2 = 2
      end
    elseif __dc_2 == 1 then
      _r0 = _G["print"]
      _r1 = "High example"
      _r0(_r1)
      __dc_2 = 2
    elseif __dc_2 == 2 then
      _r0 = 2
      if _r0 == 2 then
        __dc_2 = 3
      else
        __dc_2 = 4
      end
    elseif __dc_2 == 3 then
      _r0 = _G["print"]
      _r1 = "High example 2"
      _r0(_r1)
      __dc_2 = 4
    elseif __dc_2 == 4 then
      _r0 = 3
      if _r0 == 3 then
        __dc_2 = 5
      else
        __dc_2 = 6
      end
    elseif __dc_2 == 5 then
      _r0 = _G["print"]
      _r1 = "High example 3"
      _r0(_r1)
      __dc_2 = 6
    elseif __dc_2 == 6 then
      _r0 = 3
      if _r0 == 4 then
        __dc_2 = 7
      else
        __dc_2 = 8
      end
    elseif __dc_2 == 7 then
      _r0 = _G["print"]
      _r1 = "High example 4"
      _r0(_r1)
      __dc_2 = 8
    elseif __dc_2 == 8 then
      return
    elseif __dc_2 == 102000 then
      local __ph_2_0 = nil
    elseif __dc_2 == 102001 then
      local __ph_2_1 = nil
    else
      break
    end
  end
  return nil
end

return (function()
  return __p0()
end)()
